# Server Configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "60s"

# Database Configuration (TimescaleDB/PostgreSQL)
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "taskdb"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

# JWT Configuration
jwt:
  secret_key: "your-secret-key-change-this-in-production"
  token_expiration: "24h"
  refresh_expiration: "168h" # 7 days

# Metrics Configuration
metrics:
  enabled: true
  path: "/metrics"
  port: 8081